SELECTED_CATEGORIES = [
        ('Blazer', '2'),
        ('Bomber', '4'),
        ('Button-Down', '5'),
        ('Cardigan', '6'),
        ('Chinos', '22'),
        ('Coat', '39'),
        ('Flannel', '7'),
        ('Henley', '9'),
        ('Hoodie', '10'),
        ('Jacket', '11'),
        ('Jeans', '26'),
        ('Jersey', '12'),
        ('Joggers', '29'),
        ('Parka', '13'),
        ('Poncho', '15'),
        ('Shorts', '32'),
        ('Sweater', '16'),
        ('Sweatpants', '34'),
        ('Sweatshorts', '35'),
        ('Tank', '17'),
        ('Tee', '18'),
        ('Top', '19'),
        ('Trunks', '36')
]
